### PR TITLE
Responses to client

### LINKED ISSUE #8: Reponses to client
### Return good formatted HTTP 1.1 responses for: 

- [x] Return 401 unauthorized when /login with wrong credentials
- [x] Implement the 400 Bad request response.
- [x] 201 Created when /register is successful
- [x] 409 Conflict (in general) response. 

---

### Avoid all exceptions on the Server: 

- [x] Add **specific exceptions** when JSON is _malformed_ (no expected fields or other mistakes when parsing). Handle this exception as HTTP **Response 400** Bad Request. 
- [x] A _global exception handler process_ should be implemented (probably). All unknown exceptions should be handled as 500 Internal Error response.
---
- [x] Check that the user with the **email (unique** for customers) exists. Then **409 Conflict**  response.
- [x] Handle login when customer does not exist (password can't be found)
- [x] Check if the account has **not enough** money when transferring. **400 Bad request** (not enough money on account) response
- [x] Check that account when checking or transferring exists or is owned by the customer. 400 Bad request with a message in json otherwise.
- [x] Check that receiver's account exists when transferring money from sender. Bad Request with message should be returned
- [x] Validate registering data - email, name, surname, password must be not empty
- [x]  Check existence of user and his account when saving a new account to a user. If account exists it's ok, nothing to update in db.
- [x] A user should not have more than 5 accounts (active flag in a database). 409 response thrown.
---
- [x] Handle **JWT exception** (expiration). 401 with a message in the JSON body telling about it.

**Everything should be logged properly**
_(this issue will be expanded)_

### LINKED ISSUE #11: Forbid /manager path
Only managers and admins may refer to the routes starting with manager: /manager/**

Also, only user with role admin may check /admin/**

### PR DESCRIPTION
**Pull request by AlmetovKamil**
#8 #11 #6

### CODE REVIEW

**Review by system205 — CHANGES_REQUESTED** [review]
Remove this empty line

**Review by system205 — CHANGES_REQUESTED** [review]
123

File: src/main/java/oop/course/implementations/GetAccount.java [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package oop.course.implementations;
 
 import oop.course.entity.*;
+
```
Comment (system205) [inline src/main/java/oop/course/implementations/GetAccount.java]: remove

File: src/main/java/oop/course/implementations/GuardedUrl.java [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    }
+
+    @Override
+    public String path(Request request) {
+        String url  = request.url();
+        if (rolesConfiguration.isAllowedToGo(url)) {
+            return url;
+        }
+        String userId = new HeaderToken(request.headers()).id();
+        final Collection<String> roles = new Customer(connection, userId).roles();
```
Comment (system205) [inline src/main/java/oop/course/implementations/GuardedUrl.java]: add userId to customer constructor if no use elsewhere

File: src/main/java/oop/course/implementations/GuardedUrl.java [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+        for (String role : roles) {
+            if (this.rolesConfiguration.isAllowedToGo(url, role)) {
+                return url;
+            }
+        }
+        logger.error("User with roles " + roles + " is not allowed to go to " + url);
```
Comment (system205) [inline src/main/java/oop/course/implementations/GuardedUrl.java]: It's not an error. It is not a warning either. Replace to debug

File: src/main/java/oop/course/implementations/HeaderToken.java [hunk 4]
```diff
@@ -4,18 +4,24 @@
...
 import com.auth0.jwt.interfaces.*;
+import oop.course.exceptions.AuthorizationException;
+import oop.course.exceptions.BaseException;
 import oop.course.interfaces.*;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 import java.util.*;
 
+// TODO Add proper exceptions
```
Comment (system205) [inline src/main/java/oop/course/implementations/HeaderToken.java]: Added?

File: src/main/java/oop/course/implementations/HttpRequest.java [hunk 5]
```diff
@@ -1,30 +1,56 @@
...
+// TODO - should I throw an exception if accessing well formatted headers, but at the same time th request line is malformed?
 public class HttpRequest implements Request {
-    private final Collection<String> data;
+    private final Logger log = LoggerFactory.getLogger(HttpRequest.class);
+    private final LinkedList<String> data;
 
     public HttpRequest(BufferedReader in) throws IOException {
         this.data = new LinkedList<>();
         String line;
+        // TODO - change it to read until actual EOF
```
Comment (system205) [inline src/main/java/oop/course/implementations/HttpRequest.java]: I think I had it already

File: src/main/java/oop/course/implementations/HttpRequest.java [hunk 6]
```diff
@@ -1,30 +1,56 @@
...
         while (!(line = in.readLine()).equals("EOF")) {
             this.data.add(line);
         }
-        System.out.println(this.data);
+        log.info("HttpRequest data:\n" + this.data);
```
Comment (system205) [inline src/main/java/oop/course/implementations/HttpRequest.java]: log.info("HttpRequest data:\n{}", this.data);

File: src/main/java/oop/course/implementations/HttpRequest.java [hunk 7]
```diff
@@ -1,30 +1,56 @@
...
+            throw new MalformedDataException("Request line is malformed: " + Arrays.toString(requestLine));
+        }
+        return requestLine;
     }
 
     @Override
     public Collection<String> headers() {
         // a part of the data
-        Collection<String> headers = new ArrayList<>();
+        // TODO - multiple line headers are not implemented
```
Comment (system205) [inline src/main/java/oop/course/implementations/HttpRequest.java]: Should we implement? I think no

File: src/main/java/oop/course/implementations/SimpleUrl.java [hunk 8]
```diff
@@ -1,11 +1,12 @@
 package oop.course.implementations;
 
+
 import oop.course.interfaces.*;
 
 public class SimpleUrl implements URL {
```
Comment (system205) [inline src/main/java/oop/course/implementations/SimpleUrl.java]: Can you delete this class?

File: src/main/java/oop/course/implementations/TokenReturn.java [hunk 9]
```diff
@@ -1,6 +1,7 @@
 package oop.course.implementations;
 
 import oop.course.entity.*;
+
```
Comment (system205) [inline src/main/java/oop/course/implementations/TokenReturn.java]: should be a space?

File: src/main/java/oop/course/interfaces/Account.java [hunk 10]
```diff
@@ -15,7 +15,7 @@ public interface Account extends JSON {
 
     void save(String customerId);
 
-    CustomerRequest attachRequest(String type, BigDecimal amount);
+    CustomerRequest attachRequest(String type, BigDecimal amount) ;
```
Comment (system205) [inline src/main/java/oop/course/interfaces/Account.java]: Soryy, do you check your commits?)

File: src/main/java/oop/course/interfaces/Id.java [hunk 11]
```diff
@@ -1,5 +1,7 @@
 package oop.course.interfaces;
 
+
+
 public interface Id<T> {
-    T id();
+    T id() ;
```
Comment (system205) [inline src/main/java/oop/course/interfaces/Id.java]: Why spaces?

File: src/main/java/oop/course/responses/BaseResponse.java [hunk 12]
```diff
@@ -0,0 +1,57 @@
...
+            }
+            sb.append("\n");
+        }
+        sb.append("\n");
+        if (!body.isEmpty()) {
+            sb.append(body);
+            sb.append("\n");
+        }
+        sb.append("EOF");
+        log.info("Sent response:\n\n" + sb);
```
Comment (system205) [inline src/main/java/oop/course/responses/BaseResponse.java]: why twice \n\n. and Use {} for interpolation

File: src/main/java/oop/course/responses/MethodNotAllowedResponse.java [hunk 13]
```diff
@@ -0,0 +1,14 @@
+package oop.course.responses;
+
+import oop.course.interfaces.Response;
+
+import java.io.IOException;
+import java.io.PrintWriter;
+
+// TODO - there must be the Allowed header
```
Comment (system205) [inline src/main/java/oop/course/responses/MethodNotAllowedResponse.java]: Done or where?

File: src/main/java/oop/course/responses/MethodNotAllowedResponse.java [hunk 14]
```diff
@@ -0,0 +1,14 @@
...
+public class MethodNotAllowedResponse implements Response {
+    @Override
+    public void print(PrintWriter out) throws IOException {
+        new BaseResponse(405, "Method not allowed");
```
Comment (system205) [inline src/main/java/oop/course/responses/MethodNotAllowedResponse.java]: Should it call methods? Or just constructor

File: src/main/java/oop/course/routes/AdminFork.java [hunk 15]
```diff
@@ -1,23 +1,30 @@
...
-    public Response act(Request request) {
+    public Response act(Request request)  {
         String url = request.url().substring("/admin".length());
         for (Route r : routes) {
             if (r.accept(url)) {
                 return r.act(request);
             }
         }
-        throw new RuntimeException("Suitable route is not found in /admin");
+        log.error("Suitable route is not found in /admin");
```
Comment (system205) [inline src/main/java/oop/course/routes/AdminFork.java]: it's not error. Let it be debug

File: src/main/java/oop/course/routes/ApplicantsRoute.java [hunk 16]
```diff
@@ -1,23 +1,29 @@
...
-    public Response act(Request request) {
+    public Response act(Request request)  {
         String method = request.method();
         for (ProcessMethod m : processes) {
             if (m.accept(method)) {
                 return m.act(request);
             }
         }
-        throw new RuntimeException("Method " + method + " is not allowed in /offers");
+        log.error("Method " + method + " is not allowed in /offers");
```
Comment (system205) [inline src/main/java/oop/course/routes/ApplicantsRoute.java]: Maybe you can search what level of logger is better here. +{} for interpolation

File: src/main/java/oop/course/routes/LoginRoute.java [hunk 17]
```diff
@@ -1,20 +1,48 @@
...
         this.next = next;
     }
 
     @Override
-    public Response act(Request request) {
+    public Response act(Request request)  {
+        Form form = new JsonForm(request.body());
+        Customer customer = new Customer(connection, form);
+        if (!customer.exists()) {
+            log.error("Customer not found:\nEmail: " +
```
Comment (system205) [inline src/main/java/oop/course/routes/LoginRoute.java]: not extract from form. Let customer tell that his email or whatever does not exist. Just check the flag

File: src/main/java/oop/course/Main.java [hunk 18]
```diff
@@ -42,82 +42,80 @@ public static void main(String[] args) throws IOException, SQLException {
...
-                                                "mySecretKey",
-                                                24L * 60 * 60 * 1000,
-                                                connection
-                                        )
-                                ),
-                                new RegisterRoute( // /register
+                new Fork(
+                        new SimpleUrl(),
+                        new MainRoute(),
+                        new LoginRoute(
```
Comment (system205) [inline src/main/java/oop/course/Main.java]: you removed the comment with /path. At the end it should be preserved

**Review by system205 — CHANGES_REQUESTED** [review]
Changes required
